### ISSUE TITLE
First ToolTip wrong position.

### ISSUE THREAD

**Issue by jenokizm** [JohnyMac/AutoCompleteMenu-ScintillaNET#1]
At the first ToolTip wrong position. Then something interesting after the change of the keyword, it falls into place.

[Video bug ](https://onedrive.live.com/redir?resid=8CCB3DA84C4299AE!11030&authkey=!ALH6HkKQNb3jxYI&ithint=video%2cwmv)

**Comment by JohnyMac** [comment]
Ik about this bug but tbh since its not originally my code, can't even find the place of the bugged code lol..

Will try again and again.

**Comment by JohnyMac** [comment]
Fixed in https://github.com/JohnyMac/AutoCompleteMenu-ScintillaNET/commit/a3ba1d48378fc27ad761d870592ce4f885e0ed5f :)

**Comment by JohnyMac** [comment]
BTW, just did a nuget package for it for ease of use: https://www.nuget.org/packages/AutoCompleteMenu-ScintillaNET

**Comment by jenokizm** [comment]
Thank you for the hot fix!
Yes nuget this is a useful thing, well done uploaded)

**Comment by jenokizm** [comment]
Hi, you'll laugh) But with the latest version 3.6.3, the same thing happens as on the video I shot a year earlier) Can you make a fix again?

**Comment by Ahmad45123** [comment]
Really ? I remember it was fixed.

Anyways, I won't get to inspect and fix it soon, busy.. Feel free to fork the code and attempt yourself and don't forget to send in a PR :)

**Comment by jenokizm** [comment]
Yes, I looked at the history of the commits. You fixed it, and then broke it in the next) There's a trivial matter, it's already figured out)
